[package]
name = "doc-test"
version = "0.1.0"
authors = ["Tokio Contributors <team@tokio.rs>"]
edition = "2018"
build = "build.rs"
publish = false

[dependencies]
async-stream = "0.2"
mini-redis = "0.3"
tokio = { version = "0.3.0", features = ["full"] }
bytes = "0.6"
futures = "0.3"
doc-comment = "0.3.3"
crossbeam = "0.7"

[build-dependencies]
glob = "0.3"

[patch.crates-io]
tokio = { git = "https://github.com/tokio-rs/tokio", branch = "bring-back-read-buf" }
bytes = { git = "https://github.com/tokio-rs/bytes" }
mini-redis = { git = "https://github.com/tokio-rs/mini-redis", branch = "track-v0.3" }